[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # No GEMINI_API_KEY required - users provide their own via the UI
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

# Form handling (if needed in future)
[build.processing]
  skip_processing = false

# Edge functions config
[context.production.environment]
  NODE_ENV = "production"