[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # No GEMINI_API_KEY required - users provide their own via the UI
  NODE_VERSION = "18"
  # IMPORTANT: Do NOT set NPM_FLAGS to something like '--version' or the install step
  # on Netlify will effectively be skipped (e.g. it would run `npm install --version`).
  # That prevented node_modules (and thus 'next') from being installed and caused
  # the error: 'sh: 1: next: not found'. Leave NPM_FLAGS unset unless you need
  # safe flags like '--no-audit --no-fund'.

# Form handling (if needed in future)
[build.processing]
  skip_processing = false

# Edge functions config
[context.production.environment]
  NODE_ENV = "production"